FROM node:21-alpine
WORKDIR /home/node/app/rems-directory

COPY --chown=node:node . .
RUN npm install
EXPOSE 3323
EXPOSE 3324

HEALTHCHECK --interval=30s --start-period=15s --timeout=10m --retries=10 CMD wget --no-verbose --tries=1 --spider http://127.0.0.1:${SERVER_PORT:-3323}/health || exit 1
CMD ./dockerRunnerDev.sh
